baseurl = "https://milinddethe15.github.io"
title = "@milinddethe15"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

[pagination]
pagerSize = 20

[markup.highlight]
style = "github-dark"

[params]
  author = "Milind Dethe"
  info = [
    "Software Engineer Intern [@Atlan](https://atlan.com)",
    "LFX'24 Mentee [@CNCF Thanos](https://thanos.io/)",
    "Engineering Student [@IITKGP](https://www.iitkgp.ac.in/)"
  ]
  description = "Milind Dethe's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "/images/dp.jpg"
  #gravatar = "milinddethe15@gmail.com"
  githubUsername = "milinddethe15"
  faviconSVG = "/images/favicon.svg"
  favicon_32 = "/images/favicon-32x32.png"
  favicon_16 = "/images/favicon-16x16.png"

  since = 2025
  disableFooter = true
  
  disableDefaultJsScripts = false
  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/github-activity.css","css/github-activity.dark.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/github-activity.min.js","js/mustache.min.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "GitHub"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/milinddethe15/"

[[params.social]]
  name = "Twitter"
  icon = "fa-brands fa-x-twitter fa-2x"
  weight = 2
  url = "https://twitter.com/milinddethe15/"

[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 3
  url = "https://www.linkedin.com/in/milind-dethe/"


[[params.social]]
  name = "Instagram"
  icon = "fa-brands fa-instagram fa-2x"
  weight = 8
  url = "https://www.instagram.com/milinddethe15/"

[[params.social]]
  name = "Discord"
  icon = "fa-brands fa-discord fa-2x"
  weight = 11
  url = "https://discord.com/users/milinddethe"

[[params.social]]
  name = "Email"
  icon = "fa-solid fa-envelope fa-2x"
  weight = 13
  url = "mailto:milinddethe15@gmail.com"


# Menu links
[[menu.main]]
  name = "Posts"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "Resume"
  weight = 2
  url = "https://drive.google.com/file/d/1BbZS8mHuxcgBiR5ZlOw5_cPORrJ6X3wj/view?usp=sharing"
[[menu.main]]
  name = "Activity"
  weight = 3
  url = "activity/"
[[menu.main]]
  name = "About Me"
  weight = 4
  url = "about/"

# If you want to use Cloudflare Web Analytics(https://cloudflare.com) for analytics, add this section
[params.cloudflare]
token = "06221de30e1e4ec2870a1f8dc46d48ed"

# If you want to use Google Tag Manager(https://analytics.google.com/) for analytics, add this section
[params.googleTagManager]
id = "G-73ZGWNVCPE"
